# Generated by Django 5.0.7 on 2024-07-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ribbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CreateBouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('receiver_name', models.CharField(max_length=30)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('flower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.flower')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.package')),
                ('ribbon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.ribbon')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.size')),
            ],
        ),
    ]
